version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: always
    ports:
      - "18546:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - nextcloud_db_data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "898:80"
    depends_on:
      - db

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - "15381:80"
    env_file:
      - .env
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /www/cbnet_project/nextcloud/html:/var/www/html:/var/www/html
    depends_on:
      - db

volumes:
  nextcloud_db_data:
    driver: local
  nextcloud_data:
    driver: local
